title: Student Robotics Style Guide
description: >
  This is the Student Robotics Style Guide. This site will provide guidance on
  how best to use official Student Robotics assets, as well as how to design
  products which fit with the Student Robotics brand.
baseurl: "/style"
url: "http://studentrobotics.github.io"
markdown: kramdown
collections:
  - sections

social:
  facebook-official: https://facebook.com/StudentRobotics
  twitter: https://twitter.com/studentrobotics
  youtube: https://youtube.com/user/StudentRobotics
  github: https://github.com/srobo

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - gems/
